name: Dispatcher Workflow

on:
  workflow_dispatch:

jobs:
  check-runner:
    runs-on: windows-latest
    outputs:
      asus-online: ${{ steps.check-asus.outputs.online }}
    steps:
      - name: Check ASUS-PROART Runner
        id: check-asus
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          $label = "Asus-ProArt"
          $repo = "${{ github.repository }}"
          $apiUrl = "https://api.github.com/repos/$repo/actions/runners"
          $headers = @{
            Authorization = "Bearer $env:GH_TOKEN"
            Accept        = "application/vnd.github+json"
            "X-GitHub-Api-Version" = "2022-11-28"
          }
          $runners = Invoke-RestMethod -Uri $apiUrl -Headers $headers
          $isOnline = $false
          foreach ($runner in $runners.runners) {
            $labelNames = $runner.labels | ForEach-Object { $_.name.ToLower() }
            if ($labelNames -contains $label.ToLower() -and $runner.status -eq "online") {
              $isOnline = $true
              break
            }
          }
          "online=$($isOnline.ToString().ToLower())" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

  run-asus-tests:
    needs: check-runner
    if: needs.check-runner.outputs.asus-online == 'true'
    uses: ./.github/workflows/reusable-asus.yml
    with:
      runner_label: "Asus-ProArt"
    secrets: inherit
