name: PowerShell Tests

on:
  push:
    branches:
      - user/jdugar/TestSelfHostAgent   # Or the branch you are using

permissions:
  contents: write        # Allow write access to repository contents (e.g., pushing changes)
  pull-requests: write   # Allow write access to pull requests (e.g., create or merge PRs)
  issues: write          # Allow write access to issues (optional, if needed)
  actions: write         # Allow write access to Actions (e.g., update or create workflows)

jobs:
  test:
    runs-on: [self-hosted, windows]  # Use self-hosted runner with Windows (adjust as needed)

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures the entire history is checked out (not just the latest commit)

    - name: Run PowerShell Tests from E2e folder
      shell: powershell  # Using PowerShell Core (pwsh)
      run: |
        # Change directory to the location where the tests are located (E2e folder)
        cd E2E
        
        # Run the PowerShell test script
        .\CheckInTest.ps1  # Adjust to your actual script name

    - name: Upload test results (Optional)
      if: success()
      run: |
        # You can upload results or logs here (e.g., to GitHub artifacts or external services)
        Write-Output "Test run completed successfully"
      
    - name: Handle failure (Optional)
      if: failure()
      run: |
        # Handle test failures here (e.g., send notifications, log errors)
        Write-Output "Test run failed"
